class Book
  attr_accessor completion_date: string
  attr_accessor created_date: string
  attr_accessor delete_date: string
  attr_accessor id: int
  attr_accessor insert_date: string
  attr_accessor name: string
  attr_accessor publisher: string
  attr_accessor status: int
  attr_accessor type: int

  attr_accessor update_date: string
  attr_accessor use_yn: string

  def initialize: -> Book
end
