class ContentController
  def add_content: -> (int | nil | String)

  def find_content_on_map: -> ({ } | String)

  def get_content_list: -> (hash[Content, Page] | String)

  def get_one_content: -> (Content | String)

  def modify_content: -> (bool | String)

  def remove_content: -> (bool | String)
end
