class GroupController
  def add_group: -> (bool | String)

  def find_group_on_map: -> ( {} | String)

  def get_book_group_list_with_count: -> (hash[Group, Page] | String)

  def get_group_list: -> (array[Group] | String)

  def get_group_list_by_content_id: -> (array[Group] | String)

  def get_group_list_with_count: -> (hash[array[Group], Page] | String)

  def get_group_status_info: -> ( {} | String )

  def get_one_group: -> (Group | String)

  def get_selected_group_list: -> (array[Group] | String)

  def modify_one_group: -> (bool | String)

  def remove_mapping_group: -> (bool | String)

  def remove_one_group: -> (bool | String)

  def set_mapping_group: -> (bool | String)
end
